apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dapp-nextjs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-dapp-nextjs-app
  template:
    metadata:
      labels:
        app: my-dapp-nextjs-app
    spec:
      containers:
      - name: my-container
        image: shehroz85waseem/dapp-next:1.0
        ports:
        - containerPort: 8082
