apiVersion: v1
kind: Service
metadata:
  name: my-dapp-nextjs-app
spec:
  selector:
    app: my-dapp-nextjs-app
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer